# Generated by Django 6.0.1 on 2026-01-21 08:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_record',
            name='Applied_On',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leave_record',
            name='Start_Date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='leave_record',
            name='Status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=8),
        ),
    ]
