# Generated by Django 6.0.1 on 2026-01-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_leave_record_applied_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_record',
            name='Cancelled_By',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leave_record',
            name='Cancelled_On',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leave_record',
            name='Status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=10),
        ),
    ]
